# Generated by Django 5.0.4 on 2024-04-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
    ]
